/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.view;
import com.model.model_kasir;
import java.awt.Component;
import java.awt.dnd.DropTargetListener;
import java.sql.SQLException;
import java.util.TooManyListenersException;
import java.util.logging.Logger;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.DocumentEvent;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
/**
 *
 * @author NICOLAS JUANLY NA70
 */
public class form_kasir extends javax.swing.JFrame {
    model_kasir m = new model_kasir();
    public DefaultTableModel tblmodel;
    String header[] = {"id","JenisBaju", "Ukuran", "Harga", "Total", "JumlahBarang", "Pembayaran", "Kembalian"};
    
    /**
     * Creates new form view
     */
    public form_kasir() throws SQLException {
        initComponents();
        tblmodel = new DefaultTableModel(null, header);
        Tabel.setModel(tblmodel);
        Tabel.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        m.Tampil(this);
        SetLebarKolom();
        
    }
    

    public void Reload() throws SQLException{
        this.setVisible(false);
        new form_kasir().setVisible(true);
        
    }

    
 
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem3 = new javax.swing.JRadioButtonMenuItem();
        jDialog1 = new javax.swing.JDialog();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jTextField1 = new javax.swing.JTextField();
        kasir_1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtjenisbaju = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtharga = new javax.swing.JTextField();
        UkuranM = new javax.swing.JRadioButton();
        UkuranL = new javax.swing.JRadioButton();
        UkuranXl = new javax.swing.JRadioButton();
        UkuranXxl = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        btn_simpan = new javax.swing.JButton();
        btn_batal = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabel = new javax.swing.JTable();
        txtId = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btn_hitung = new javax.swing.JButton();
        Tambah = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnHapus = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        Bayar = new javax.swing.JTextField();
        btn_BayarSekarang = new javax.swing.JButton();
        kembalian = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Jumlah_Barang = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        jLabel5.setText("Extra Size");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("jRadioButtonMenuItem2");

        jRadioButtonMenuItem3.setSelected(true);
        jRadioButtonMenuItem3.setText("jRadioButtonMenuItem3");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kasir_1.setBackground(new java.awt.Color(51, 204, 255));

        jLabel1.setFont(new java.awt.Font("Gill Sans MT", 3, 18)); // NOI18N
        jLabel1.setText("KASIR");

        txtjenisbaju.setBackground(new java.awt.Color(204, 204, 204));
        txtjenisbaju.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "batik", "kemeja", "kaos", "kebaya" }));
        txtjenisbaju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjenisbajuActionPerformed(evt);
            }
        });

        jLabel2.setText("Jenis Baju");

        jLabel3.setText("Ukuran");

        jLabel4.setText("Harga");

        txtharga.setBackground(new java.awt.Color(204, 204, 204));
        txtharga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthargaActionPerformed(evt);
            }
        });

        buttonGroup1.add(UkuranM);
        UkuranM.setSelected(true);
        UkuranM.setText("M");
        UkuranM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UkuranMActionPerformed(evt);
            }
        });

        buttonGroup1.add(UkuranL);
        UkuranL.setText("L");

        buttonGroup1.add(UkuranXl);
        UkuranXl.setText("XL");
        UkuranXl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UkuranXlActionPerformed(evt);
            }
        });

        buttonGroup1.add(UkuranXxl);
        UkuranXxl.setText("XXL");
        UkuranXxl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UkuranXxlMouseClicked(evt);
            }
        });

        jLabel6.setText("TOTAL");

        txttotal.setBackground(new java.awt.Color(204, 204, 204));
        txttotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalActionPerformed(evt);
            }
        });

        btn_simpan.setText("SIMPAN");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        btn_batal.setText("BATAL");
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        Tabel.setBackground(new java.awt.Color(204, 204, 204));
        Tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Jenis Baju", "Ukuran", "Harga", "Total", "Jumlah Barang", "Pembayaran", "Kembalian"
            }
        ));
        Tabel.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                TabelAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        Tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabel);

        txtId.setBackground(new java.awt.Color(204, 204, 204));

        jLabel7.setText("ID");

        btn_hitung.setText("Hitung");
        btn_hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hitungActionPerformed(evt);
            }
        });

        Tambah.setBackground(new java.awt.Color(204, 204, 204));
        Tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahActionPerformed(evt);
            }
        });

        jLabel8.setText("Tambahan");

        btnHapus.setText("HAPUS");
        btnHapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHapusMouseClicked(evt);
            }
        });
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        jLabel9.setText("BAYAR");

        Bayar.setBackground(new java.awt.Color(204, 204, 204));

        btn_BayarSekarang.setText("BAYAR SEKARANG");
        btn_BayarSekarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BayarSekarangActionPerformed(evt);
            }
        });

        kembalian.setBackground(new java.awt.Color(204, 204, 204));
        kembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembalianActionPerformed(evt);
            }
        });

        jLabel10.setText("KEMBALI");

        Jumlah_Barang.setBackground(new java.awt.Color(204, 204, 204));

        jLabel11.setText("Jumlah barang");

        javax.swing.GroupLayout kasir_1Layout = new javax.swing.GroupLayout(kasir_1);
        kasir_1.setLayout(kasir_1Layout);
        kasir_1Layout.setHorizontalGroup(
            kasir_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kasir_1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kasir_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
                    .addGroup(kasir_1Layout.createSequentialGroup()
                        .addGroup(kasir_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kasir_1Layout.createSequentialGroup()
                                .addGroup(kasir_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(kasir_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(kasir_1Layout.createSequentialGroup()
                                        .addGroup(kasir_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(Tambah, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtId)
                                            .addComponent(txtjenisbaju, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, kasir_1Layout.createSequentialGroup()
                                                .addComponent(UkuranM)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(UkuranL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(txtharga))
                                        .addGroup(kasir_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(kasir_1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(kasir_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(kasir_1Layout.createSequentialGroup()
                                                        .addGroup(kasir_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(kasir_1Layout.createSequentialGroup()
                                                                .addComponent(UkuranXl)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(UkuranXxl)
                                                                .addGap(196, 196, 196))
                                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kasir_1Layout.createSequentialGroup()
                                                                .addGroup(kasir_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                                        .addGroup(kasir_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(Bayar)
                                                            .addComponent(Jumlah_Barang)
                                                            .addComponent(kembalian)))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kasir_1Layout.createSequentialGroup()
                                                        .addGap(0, 0, Short.MAX_VALUE)
                                                        .addComponent(btn_BayarSekarang)
                                                        .addGap(39, 39, 39))))
                                            .addGroup(kasir_1Layout.createSequentialGroup()
                                                .addGap(152, 152, 152)
                                                .addComponent(jLabel1)
                                                .addGap(0, 0, Short.MAX_VALUE))))))
                            .addGroup(kasir_1Layout.createSequentialGroup()
                                .addComponent(btn_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(119, 119, 119)
                                .addComponent(btn_hitung, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnHapus)
                                .addGap(58, 58, 58)))
                        .addGap(25, 25, 25)
                        .addComponent(btn_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        kasir_1Layout.setVerticalGroup(
            kasir_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kasir_1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kasir_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kasir_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kasir_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtjenisbaju, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kasir_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(kasir_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(UkuranM)
                        .addComponent(UkuranL)
                        .addComponent(UkuranXl)
                        .addComponent(UkuranXxl)
                        .addComponent(Jumlah_Barang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)))
                .addGap(15, 15, 15)
                .addGroup(kasir_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kasir_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kasir_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Tambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8))
                    .addComponent(btn_BayarSekarang, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(kasir_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kasir_1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(kasir_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(kasir_1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(kasir_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(kembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(13, 13, 13)
                .addGroup(kasir_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_simpan)
                    .addComponent(btn_hitung)
                    .addComponent(btnHapus)
                    .addComponent(btn_batal))
                .addGap(8, 8, 8)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kasir_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kasir_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtjenisbajuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjenisbajuActionPerformed
        String JenisBarang=(String)txtjenisbaju.getSelectedItem();
        switch(JenisBarang){
            case "batik" :
                txtharga.setText("30000");
            break;
             case "kemeja" :
                txtharga.setText("50000");
            break;
             case "kaos" :
                txtharga.setText("35000");
            break;
             case "kebaya" :
                txtharga.setText("42000");
            break;
        }
        
        
    }//GEN-LAST:event_txtjenisbajuActionPerformed

    private void UkuranXlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UkuranXlActionPerformed
    Tambah.setText("10000");
   
       
       
      
    }//GEN-LAST:event_UkuranXlActionPerformed

    private void txttotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttotalActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
         try {
            //isi kode penanganan program
            m.Simpan(this);
            Reload();
        } catch (SQLException ex) {
            Logger.getLogger(form_kasir.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void UkuranMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UkuranMActionPerformed
      
    }//GEN-LAST:event_UkuranMActionPerformed

    private void TabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelMouseClicked
        // TODO add your handling code here:
       try{
           m.KlikTable(this);
       } catch (SQLException ex){
           Logger.getLogger(form_kasir.class.getName()).log(Level.SEVERE, null, ex);
       }
    }//GEN-LAST:event_TabelMouseClicked

    private void txthargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthargaActionPerformed
    
    
    }//GEN-LAST:event_txthargaActionPerformed

    private void TambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TambahActionPerformed

    private void btn_hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hitungActionPerformed
        // TODO add your handling code here:
        int bil1;
        int bil2;
        int bil3;
        int hasil;
        bil1=Integer.parseInt(txtharga.getText());
        bil2=Integer.parseInt(Tambah.getText());
        bil3=Integer.parseInt(Jumlah_Barang.getText());
        hasil = bil1*bil3+bil2*bil3;
        
        txttotal.setText(Integer.toString(hasil));
        
    }//GEN-LAST:event_btn_hitungActionPerformed

    private void btnHapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapusMouseClicked
        try{
            //isi kode penanganan program
            m.Hapus(this);
        } catch(Exception ex){
            Logger.getLogger(form_kasir.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnHapusMouseClicked

    private void UkuranXxlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UkuranXxlMouseClicked
        Tambah.setText("10000");
       
    }//GEN-LAST:event_UkuranXxlMouseClicked

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed

         try {
            //isi kode penanganan program
            m.Hapus(this);
            Reload();
        } catch (SQLException ex) {
            Logger.getLogger(form_kasir.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        // TODO add your handling code here:
       dispose();
        try {
            Reload();
        } catch (SQLException ex) {
            Logger.getLogger(form_kasir.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_batalActionPerformed

    private void btn_BayarSekarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BayarSekarangActionPerformed
        // TODO add your handling code here:
        int a ;
        int b ;
        int hasil;
        
        a=Integer.parseInt(Bayar.getText());
        b=Integer.parseInt(txttotal.getText());
        hasil = a-b;
        kembalian.setText(Integer.toString(hasil));
        
        
    }//GEN-LAST:event_btn_BayarSekarangActionPerformed

    private void TabelAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_TabelAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_TabelAncestorAdded

    private void kembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembalianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kembalianActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new form_kasir().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(form_kasir.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Bayar;
    private javax.swing.JTextField Jumlah_Barang;
    public javax.swing.JTable Tabel;
    public javax.swing.JTextField Tambah;
    public javax.swing.JRadioButton UkuranL;
    public javax.swing.JRadioButton UkuranM;
    public javax.swing.JRadioButton UkuranXl;
    public javax.swing.JRadioButton UkuranXxl;
    public javax.swing.JButton btnHapus;
    private javax.swing.JButton btn_BayarSekarang;
    public javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_hitung;
    public javax.swing.JButton btn_simpan;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel kasir_1;
    private javax.swing.JTextField kembalian;
    public javax.swing.JTextField txtId;
    public javax.swing.JTextField txtharga;
    public javax.swing.JComboBox<String> txtjenisbaju;
    public javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
    private void SetLebarKolom() {

    }

}


